export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS"
export const GET_CHARACTERS_NOTHING = "GET_CHARACTERS_NOTHING"

export const GET_CHARACTER_SUCCESS = "GET_CHARACTER_SUCCESS"
export const GET_CHARACTER_NOTHING = "GET_CHARACTER_NOTHING"